=== UO270656/BOOKSHEW/fase2_Desarrollo/libros.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro  (fecha_publicacion, paginas, editorial, descripcion, target, autor, recomendacion, bibliotecas)>
<!ELEMENT fecha_publicacion (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT bibliotecas (biblioteca+)>
<!ELEMENT biblioteca (long_biblioteca, lat_biblioteca, alt_biblioteca)>
<!ELEMENT long_biblioteca (#PCDATA)>
<!ELEMENT lat_biblioteca (#PCDATA)>
<!ELEMENT alt_biblioteca (#PCDATA)>
<!ATTLIST libro nombre CDATA #REQUIRED>
<!ATTLIST libro tipo CDATA #REQUIRED>
<!ATTLIST libro dificultad CDATA #REQUIRED>
<!ATTLIST biblioteca nombre CDATA #REQUIRED>
<!ATTLIST alt_biblioteca unidades CDATA #REQUIRED>

=== UO270656/BOOKSHEW/fase2_Desarrollo/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "libros.dtd">
<libros>
  <libro nombre="Hijos de Virtud y Venganza" tipo="Fantasia" dificultad="media">
    <fecha_publicacion formato="DD/MM/AAAA">28/3/2020</fecha_publicacion>
    <paginas>489</paginas>
    <editorial>RBA</editorial>
    <descripcion>La magia ha regresado al país de Orïsha... Pero la lucha por el poder no ha terminado. La guerra acaba de empezar.</descripcion>
    <target>+6</target>
    <autor>Tomi Adeyemi</autor>
    <tiendas> 
      <tienda>https://www.google.com/url?sa=t&amp;rct=j&amp;q=&amp;esrc=s&amp;source=web&amp;cd=&amp;cad=rja&amp;uact=8&amp;ved=2ahUKEwjLmfCsop_xAhWK3oUKHSCJBBUQFjABegQIAxAE&amp;url=https%3A%2F%2Fwww.amazon.es%2FHijos-virtud-venganza-FICCI%25C3%2593N-YA%2Fdp%2F8427213476&amp;usg=AOvVaw0cYEmupShMzbh_BKh3sI0X</tienda>
      <tienda>https://www.casadellibro.com/libro-hijos-de-virtud-y-venganza-legado-de-orisha-2/9788427213470/11366516</tienda>
      <tienda>https://www.elcorteingles.es/libros/A34802104-hijos-de-virtud-y-venganza-tapa-blanda/</tienda>
    </tiendas>
    <recomendacion>7</recomendacion>
    <bibliotecas>
      <biblioteca nombre="Sán Lázaro"> 
        <long_biblioteca>43.353091075300554</long_biblioteca>
        <lat_biblioteca>-5.841920397615947</lat_biblioteca>
        <alt_biblioteca unidades="metros">300</alt_biblioteca>
      </biblioteca>
      <biblioteca nombre="Pumarín">
        <long_biblioteca>43.37061439491936</long_biblioteca>
        <lat_biblioteca>-5.841029851391064</lat_biblioteca>
        <alt_biblioteca unidades="metros">220</alt_biblioteca>
      </biblioteca>
      <biblioteca nombre="La corredoria">
        <long_biblioteca>43.38364069596293</long_biblioteca>
        <lat_biblioteca>-5.825038743422987</lat_biblioteca>
        <alt_biblioteca unidades="metros">190</alt_biblioteca>
      </biblioteca>
    </bibliotecas>
  </libro>
  <libro nombre="Trueno" tipo="Distopía" dificultad="media">
    <fecha_publicacion formato="DD/MM/AAAA">26/7/2020</fecha_publicacion>
    <paginas>721</paginas>
    <editorial>Nocturna</editorial>
    <descripcion>Todo cambió hace tres años: fue entonces cuando Anastasia y Lucifer desaparecieron; cuando el segador Goddard llegó al poder; cuando el Nimbo retiró la palabra a toda la humanidad, menos a Grayson Tolliver.</descripcion>
    <target>+12</target>
    <autor>Neal Shusterman</autor>
    <tiendas>
      <tienda>https://www.ebay.es/itm/174494553048?chn=ps&amp;norover=1&amp;mkevt=1&amp;mkrid=1185-146825-5486-0&amp;mkcid=2&amp;itemid=174494553048&amp;targetid=1278365036821&amp;device=c&amp;mktype=pla&amp;googleloc=1005509&amp;poi=&amp;campaignid=9557020799&amp;mkgroupid=127894017492&amp;rlsatarget=pla-1278365036821&amp;abcId=1139526&amp;merchantid=116402421&amp;gclid=Cj0KCQjw5auGBhDEARIsAFyNm9E_KNAGfEfUASwmwhNKVQjy88fQYDQKj-8zzo9wMV1yHyvgKKZ1cqQaAnLvEALw_wcB</tienda>
      <tienda>https://www.iberlibro.com/Trueno-Literatura-M%C3%83%C2%A1gica-Spanish-Edition-Shusterman/30805467837/bd?cm_mmc=ggl-_-ES_Shopp_TradeStandard-_-product_id=ES9788417834616USED-_-keyword=&amp;gclid=Cj0KCQjw5auGBhDEARIsAFyNm9EYIXUndFLeaG-L8XEQwrb2uWNTpaek3DdqBzjsnmSmFHUXJ2Jz10MaAp3UEALw_wcB</tienda>
      <tienda>https://www.amazon.es/Trueno-Literatura-M%C3%A1gica-Neal-Shusterman/dp/8417834613/ref=asc_df_8417834613/?tag=googshopes-21&amp;linkCode=df0&amp;hvadid=439747624981&amp;hvpos=&amp;hvnetw=g&amp;hvrand=18111923608256743929&amp;hvpone=&amp;hvptwo=&amp;hvqmt=&amp;hvdev=c&amp;hvdvcmdl=&amp;hvlocint=&amp;hvlocphy=1005509&amp;hvtargid=pla-922684299763&amp;psc=1&amp;tag=&amp;ref=&amp;adgrpid=101788041963&amp;hvpone=&amp;hvptwo=&amp;hvadid=439747624981&amp;hvpos=&amp;hvnetw=g&amp;hvrand=18111923608256743929&amp;hvqmt=&amp;hvdev=c&amp;hvdvcmdl=&amp;hvlocint=&amp;hvlocphy=1005509&amp;hvtargid=pla-922684299763</tienda>
    </tiendas>
    <recomendacion>9</recomendacion>
    <bibliotecas>
      <biblioteca nombre="Ramón Pérez Ayala">
        <long_biblioteca>43.3595540241098</long_biblioteca>
        <lat_biblioteca>-5.846433816577243</lat_biblioteca>
        <alt_biblioteca unidades="metros">250</alt_biblioteca>
      </biblioteca>
      <biblioteca nombre="Sán Lázaro"> 
        <long_biblioteca>43.353091075300554</long_biblioteca>
        <lat_biblioteca>-5.841920397615947</lat_biblioteca>
        <alt_biblioteca unidades="metros">300</alt_biblioteca>
      </biblioteca>
      <biblioteca nombre="José María Laso Prieto">
        <long_biblioteca>43.36923568259655</long_biblioteca>
        <lat_biblioteca>-5.826436385704373</lat_biblioteca>
        <alt_biblioteca unidades="metros">190</alt_biblioteca>
      </biblioteca>
    </bibliotecas>
  </libro>
  <libro nombre="Por trece razones" tipo="Drama" dificultad="baja">
    <fecha_publicacion formato="DD/MM/AAAA">20/3/2007</fecha_publicacion>
    <paginas>301</paginas>
    <editorial>Nube de tinta</editorial>
    <descripcion>Una caja, trece caras de casete, trece culpables y una víctima
    </descripcion>
    <target>+16</target>
    <autor>Jay Asher</autor>
    <tiendas>
      <tienda>https://www.amazon.es/razones-edici%C3%B3n-limitada-especial-CAMPA%C3%91AS/dp/8413142180/ref=asc_df_8413142180/?tag=googshopes-21&amp;linkCode=df0&amp;hvadid=497304514235&amp;hvpos=&amp;hvnetw=g&amp;hvrand=8592147822786035338&amp;hvpone=&amp;hvptwo=&amp;hvqmt=&amp;hvdev=c&amp;hvdvcmdl=&amp;hvlocint=&amp;hvlocphy=1005509&amp;hvtargid=pla-1228851484495&amp;psc=1</tienda>
      <tienda>https://www.casadellibro.com/libro-por-trece-razones-campana-verano---ed-limitada-a-precio-especial/9788413142180/12270993?gclid=Cj0KCQjw5auGBhDEARIsAFyNm9EPISWmZzz0UzYBL2araOX0Gb6Oa3NGt2dso6xLodfRH0QzgS7bfNcaAqS5EALw_wcB</tienda>
      <tienda>https://www.iberlibro.com/13-Reasons-Why-Asher-Jay-Razorbill/30346945262/bd?cm_mmc=ggl-_-ES_Shopp_TradeStandard-_-product_id=ES9780451478290NEW-_-keyword=&amp;gclid=Cj0KCQjw5auGBhDEARIsAFyNm9FLozwZz8wARw44BtEXkBi_VkQEWX9I7jqR_IbSlc-3nfH589hBIdcaAhO-EALw_wcB</tienda>
    </tiendas>
    <recomendacion>6</recomendacion>
    <bibliotecas>
      <biblioteca nombre="Pumarín">
        <long_biblioteca>43.37061439491936</long_biblioteca>
        <lat_biblioteca>-5.841029851391064</lat_biblioteca>
        <alt_biblioteca unidades="metros">220</alt_biblioteca>
      </biblioteca>
      <biblioteca nombre="La Granja">
        <long_biblioteca>43.36148734759308</long_biblioteca>
        <lat_biblioteca>-5.851424121346731</lat_biblioteca>
        <alt_biblioteca unidades="metros">250</alt_biblioteca>
      </biblioteca>
      <biblioteca nombre="Villa Magdalena">
        <long_biblioteca>43.36129621483267</long_biblioteca>
        <lat_biblioteca>-5.858768918006671</lat_biblioteca>
        <alt_biblioteca unidades="metros">260</alt_biblioteca>
      </biblioteca>
    </bibliotecas>
  </libro>
</libros>
